version: "2.4"
services:
  adguardhome:
    image: adguard/adguardhome
    container_name: adguardhome-${POSTFIX:-0}
    ports:
      - 53:53/tcp # first disable resolvd https://hub.docker.com/r/adguard/adguardhome#resolved-daemon 
      - 53:53/udp
      - 784:784/udp # DNS-over-Quick  --- my favourite
      - 853:853/tcp  # DNS-over-TLS
      - 3000:3000/tcp
      - 5443:5443/udp  # DNSCrypt
      - 5443:5443/tcp
      - ${ADGUARD_HOME_HTTP_PORT:-80}:80/tcp
      - ${ADGUARD_HOME_HTTPS_PORT:-443}:443/tcp
    volumes:
      - adguardhome_volume_w_${POSTFIX:-0}:/opt/adguardhome/work
      - adguardhome_volume_c_${POSTFIX:-0}:/opt/adguardhome/conf
    restart: unless-stopped
    
volumes:
  adguardhome_volume_w_${POSTFIX:-0}:
  adguardhome_volume_c_${POSTFIX:-0}:
