
version: '2.4'

services:
  uptime-kuma:
    image: louislam/uptime-kuma
    container_name: uptime-kuma-${POSTFIX:-0}
    mem_limit: 512M
    volumes:
      - uptime-kuma-data:/app/data
    ports:
      - 3001:3001  
    restart: always
    
volumes:
  uptime-kuma-data:
