version: '2.4'

services:

  pdns-recursor:
    image: pschiffe/pdns-recursor:${RECURSOR_TAG:-latest}
    environment:
      - PDNS_webserver=yes
      - PDNS_webserver_address=0.0.0.0
      - PDNS_api_key=${PDNS_API_KEY:-$$2b$$12$$rUmNjKZoWsPcVC.Yx1t38u}
      #- PDNS_webserver_allow_from=172.6.0.0/16
      - PDNS_webserver_password=${PDNS_WEBSERVER_PASSWORD:-aLLMostSecret} 
    networks:
      - pdns
    volumes:
      - /etc/localtime:/etc/localtime:ro
    ports:
      - '${BIND_IP:-0.0.0.0}:53:53'
      - '${BIND_IP:-0.0.0.0}:53:53/udp'  

  mariadb:
    image: mariadb:10.11
    networks:
      pdns:
        aliases:
          - db
          - mysql
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - mariadb:/var/lib/mysql:z
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-notYourDb}
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      timeout: 10s
      retries: 5

  phpmyadmin:
    image: phpmyadmin:5
    networks:
      - pdns
    ports:
      - '${BIND_IP:-0.0.0.0}:8988:80'
    volumes:
      - /etc/localtime:/etc/localtime:ro

  pdns-master:
    image: pschiffe/pdns-mysql:${PDNS_MYSQL_TAG:-latest}
    hostname: ns1.example.com
    networks:
      pdns:
        ipv4_address: 172.6.0.20
        aliases:
          - pdns
    extra_hosts:
      - 'ns1.example.com:172.6.0.20'
      - 'ns2.example.com:172.6.0.21'
    volumes:
      - /etc/localtime:/etc/localtime:ro
    environment:
      - PDNS_gmysql_password=${MYSQL_ROOT_PASSWORD:-notYourDb}
      - PDNS_master=yes
      - PDNS_api=yes
      - PDNS_api_key=${PDNS_API_KEY:-$$2b$$12$$rUmNjKZoWsPcVC.Yx1t38u}
      - PDNS_webserver=yes
      - PDNS_webserver_address=0.0.0.0
      - PDNS_webserver_allow_from=172.6.0.0/16
      - PDNS_version_string=anonymous
      - PDNS_default_ttl=1500
      - PDNS_allow_axfr_ips=172.6.0.21
      - PDNS_only_notify=172.6.0.21
    depends_on:
      - mariadb

  pdns-slave:
    image: pschiffe/pdns-mysql:${PDNS_MYSQL_TAG:-latest}
    hostname: ns2.example.com
    networks:
      pdns:
        ipv4_address: 172.6.0.21
    extra_hosts:
      - 'ns1.example.com:172.6.0.20'
      - 'ns2.example.com:172.6.0.21'
    volumes:
      - /etc/localtime:/etc/localtime:ro
    environment:
      - PDNS_gmysql_dbname=powerdnsslave
      - PDNS_gmysql_password=${MYSQL_ROOT_PASSWORD:-notYourDb}
      - PDNS_slave=yes
      - PDNS_superslave=yes
      - PDNS_webserver=yes
      - PDNS_webserver_address=0.0.0.0
      - PDNS_webserver_allow_from=172.6.0.0/16
      - PDNS_version_string=anonymous
      - PDNS_disable_axfr=yes
      - PDNS_allow_notify_from=172.6.0.20
      - SUPERMASTER_IPS=172.6.0.20
    depends_on:
      - mariadb
      - pdns-master

  pdns-admin-uwsgi:
    image: pschiffe/pdns-admin-uwsgi
    networks:
      pdns:
        aliases:
          - pdns-admin-uwsgi
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - pdns-admin-upload:/opt/powerdns-admin/upload
    environment:
      - PDNS_ADMIN_SQLA_DB_PASSWORD='${MYSQL_ROOT_PASSWORD:-notYourDb}'
      - PDNS_VERSION=4.7
      - PDNS_API_KEY=${PDNS_API_KEY:-$$2b$$12$$rUmNjKZoWsPcVC.Yx1t38u}
    depends_on:
      - mariadb
      - pdns-master

  pdns-admin-static:
    image: pschiffe/pdns-admin-static
    networks:
      - pdns
    ports:
      - '${BIND_IP:-0.0.0.0}:8989:80'
    volumes:
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - pdns-admin-uwsgi

networks:
  pdns:
    ipam:
      config:
        - subnet: 172.6.0.0/16
          gateway: 172.6.0.1

volumes:
  mariadb:
  pdns-admin-upload: